version: '2'
services:
    bmsapp-app:
        image: bmsapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://bmsapp-mysql:3306/bmsapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=bmsapp-elasticsearch:9300
        ports:
            - 8080:8080
    bmsapp-mysql:
        extends:
            file: mysql.yml
            service: bmsapp-mysql
    bmsapp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: bmsapp-elasticsearch
